### PR TITLE
change log - add request body in preflight scripts

### PR DESCRIPTION
**Pull request by Jephuff**

### CODE REVIEW

**Review by cheapsteak — APPROVED** [review]

**Comment by Jephuff** [comment]
> This should perhaps be grouped into the same changelog as exposing CryptoJS? Not as useful one without the other

Can do, I'll wait for that to merge and then update this PR 👍

**Review by papollosc — APPROVED** [review]

**Comment by papollosc** [comment]
@Jephuff Let's not forget to add it in the docs too?

**Comment by Jephuff** [comment]
> @Jephuff Let's not forget to add it in the docs too?

Yep! PR up for that :) https://github.com/apollographql/apollo/pull/1307

**Comment by papollosc** [comment]
🙏

**Comment by Jephuff** [comment]
Updated to include both! :)

**Pull request merged**
